/********************************************************************************
** Form generated from reading UI file 'EDCHost19.ui'
**
** Created by: Qt User Interface Compiler version 5.9.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_EDCHOST19_H
#define UI_EDCHOST19_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_EDCHost19Class
{
public:
    QWidget *centralWidget;
    QPushButton *btnMatch;
    QPushButton *btnDebug;
    QPushButton *btnPerspect;
    QLabel *lblMainBGN;

    void setupUi(QMainWindow *EDCHost19Class)
    {
        if (EDCHost19Class->objectName().isEmpty())
            EDCHost19Class->setObjectName(QStringLiteral("EDCHost19Class"));
        EDCHost19Class->resize(750, 600);
        EDCHost19Class->setMinimumSize(QSize(750, 600));
        EDCHost19Class->setMaximumSize(QSize(750, 600));
        EDCHost19Class->setStyleSheet(QLatin1String("/* Palette generated by Material Palette - materialpalette.com/green/green */\n"
"\n"
".dark-primary-color    { background: #388E3C; }\n"
".default-primary-color { background: #4CAF50; }\n"
".light-primary-color   { background: #C8E6C9; }\n"
".text-primary-color    { color: #FFFFFF; }\n"
".accent-color          { background: #4CAF50; }\n"
".primary-text-color    { color: #212121; }\n"
".secondary-text-color  { color: #757575; }\n"
".divider-color         { border-color: #BDBDBD; }\n"
""));
        centralWidget = new QWidget(EDCHost19Class);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        btnMatch = new QPushButton(centralWidget);
        btnMatch->setObjectName(QStringLiteral("btnMatch"));
        btnMatch->setGeometry(QRect(300, 400, 150, 60));
        btnDebug = new QPushButton(centralWidget);
        btnDebug->setObjectName(QStringLiteral("btnDebug"));
        btnDebug->setGeometry(QRect(575, 525, 100, 40));
        btnPerspect = new QPushButton(centralWidget);
        btnPerspect->setObjectName(QStringLiteral("btnPerspect"));
        btnPerspect->setGeometry(QRect(450, 525, 100, 40));
        lblMainBGN = new QLabel(centralWidget);
        lblMainBGN->setObjectName(QStringLiteral("lblMainBGN"));
        lblMainBGN->setGeometry(QRect(0, 0, 750, 600));
        EDCHost19Class->setCentralWidget(centralWidget);
        lblMainBGN->raise();
        btnMatch->raise();
        btnDebug->raise();
        btnPerspect->raise();

        retranslateUi(EDCHost19Class);
        QObject::connect(btnMatch, SIGNAL(clicked()), EDCHost19Class, SLOT(OnMatch()));
        QObject::connect(btnPerspect, SIGNAL(clicked()), EDCHost19Class, SLOT(OnPerspective()));
        QObject::connect(btnDebug, SIGNAL(clicked()), EDCHost19Class, SLOT(OnDebug()));

        QMetaObject::connectSlotsByName(EDCHost19Class);
    } // setupUi

    void retranslateUi(QMainWindow *EDCHost19Class)
    {
        EDCHost19Class->setWindowTitle(QApplication::translate("EDCHost19Class", "EDC19\344\270\212\344\275\215\346\234\272", Q_NULLPTR));
        btnMatch->setText(QApplication::translate("EDCHost19Class", "\350\277\233\345\205\245\346\257\224\350\265\233", Q_NULLPTR));
        btnDebug->setText(QApplication::translate("EDCHost19Class", "\350\260\203\350\257\225\344\277\241\346\201\257", Q_NULLPTR));
        btnPerspect->setText(QApplication::translate("EDCHost19Class", "\350\256\276\347\275\256\351\200\217\350\247\206", Q_NULLPTR));
        lblMainBGN->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class EDCHost19Class: public Ui_EDCHost19Class {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_EDCHOST19_H
